"""
core/writer.py — Final Output Assembler

Responsible for assembling:
- parsed metadata
- LLM explanations
- markdown formatting utilities

into a clean, structured documentation file.
"""

import datetime
from core.markdown import MarkdownBuilder  # your markdown.py builder


def assemble_documentation(
    parsed: dict,
    ai_output: dict,
    *,
    project_name: str = None,
    include_timestamp: bool = True,
    include_footer: bool = True
):
    """
    Assemble final documentation using parsed code + AI explanations.

    Parameters
    ----------
    parsed : dict
        Structured metadata from parser.py
        Example:
            {
              "raw": "...",
              "imports": [...],
              "classes": [...],
              "functions": [...]
            }

    ai_output : dict
        LLM-generated descriptions, explanations, summaries.
        Expected keys:
            {
              "overview": str,
              "class_docs": {class_name: str},
              "function_docs": {function_name: str}
            }

    project_name : str, optional
        Header metadata for document.

    include_timestamp : bool
        Adds ISO timestamp at top of document.

    include_footer : bool
        Adds "Generated by Autonomous DocAgent" at bottom.

    Returns
    -------
    str
        Final assembled Markdown document.
    """

    md = MarkdownBuilder()

    # --------------------------------------------
    # 1. Title Section
    # --------------------------------------------
    title = project_name or "Project Documentation"
    md.add_header(title, level=1)

    if include_timestamp:
        timestamp = datetime.datetime.now().isoformat()
        md.add_paragraph(f"**Generated on:** {timestamp}")

    md.add_newline()

    # --------------------------------------------
    # 2. Overview / Executive Summary
    # --------------------------------------------
    if "overview" in ai_output:
        md.add_header("Overview", level=2)
        md.add_paragraph(ai_output["overview"])
        md.add_newline()

    # --------------------------------------------
    # 3. Table of Contents
    # --------------------------------------------
    md.add_header("Table of Contents", level=2)
    md.add_table_of_contents([
        "Overview",
        "Imports",
        "Classes",
        "Functions",
        "Raw Code"
    ])
    md.add_newline()

    # --------------------------------------------
    # 4. Imports Section
    # --------------------------------------------
    md.add_header("Imports", level=2)
    if parsed.get("imports"):
        for imp in parsed["imports"]:
            md.add_bullet(f"{imp}")
    else:
        md.add_paragraph("No imports found.")
    md.add_newline()

    # --------------------------------------------
    # 5. Classes Section
    # --------------------------------------------
    md.add_header("Classes", level=2)
    if parsed.get("classes"):
        for cls in parsed["classes"]:
            md.add_header(cls["name"], level=3)

            # AI-generated documentation for this class
            if ai_output.get("class_docs", {}).get(cls["name"]):
                md.add_paragraph(ai_output["class_docs"][cls["name"]])

            # Base classes
            if cls.get("bases"):
                md.add_paragraph("**Bases:** " + ", ".join(cls["bases"]))

            # Methods
            if cls.get("methods"):
                md.add_header("Methods", level=4)
                for m in cls["methods"]:
                    md.add_bullet(m["name"])

            md.add_newline()
    else:
        md.add_paragraph("No classes found.")
        md.add_newline()

    # --------------------------------------------
    # 6. Functions Section
    # --------------------------------------------
    md.add_header("Functions", level=2)
    if parsed.get("functions"):
        for fn in parsed["functions"]:
            md.add_header(fn["name"], level=3)

            # AI function documentation
            if ai_output.get("function_docs", {}).get(fn["name"]):
                md.add_paragraph(ai_output["function_docs"][fn["name"]])

            # Signature
            if fn.get("args"):
                md.add_paragraph("**Parameters:**")
                for arg in fn["args"]:
                    md.add_bullet(arg)

            md.add_newline()
    else:
        md.add_paragraph("No standalone functions found.")
        md.add_newline()

    # --------------------------------------------
    # 7. Raw Code Section
    # --------------------------------------------
    md.add_header("Raw Code", level=2)
    md.add_code_block(parsed.get("raw", ""), lang="python")
    md.add_newline()

    # --------------------------------------------
    # 8. Footer
    # --------------------------------------------
    if include_footer:
        md.add_horizontal_rule()
        md.add_paragraph("Generated by Autonomous DocAgent")

    # --------------------------------------------
    # OUTPUT
    # --------------------------------------------
    return md.to_markdown()
